---
# Source: litmus/charts/mongodb/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: chaos-mongodb
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-12.1.11
    app.kubernetes.io/instance: chaos
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mongodb
type: Opaque
data:
  mongodb-root-password: "MTIzNA=="
  mongodb-replica-set-key: "MEJnTVNMTGlieA=="
