---
# Source: litmus/charts/mongodb/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos-mongodb
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-12.1.11
    app.kubernetes.io/instance: chaos
    app.kubernetes.io/managed-by: Helm
secrets:
  - name: chaos-mongodb
automountServiceAccountToken: true
