---
# Source: litmus/templates/auth-server-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: chaos-litmus-auth-server-service
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: litmus-auth-server
    app.kubernetes.io/instance: chaos
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: litmus
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/version: "3.0.0"
    helm.sh/chart: litmus-3.0.0
    litmuschaos.io/version: 3.0.0
spec:
  type: ClusterIP
  ports:
    - name: auth-server
      port: 9003
      targetPort: 3000
    - name: auth-rpc-server
      port: 3030
      targetPort: 3030
  selector:
    app.kubernetes.io/component: litmus-auth-server
