---
# Source: litmus/templates/controlplane-configs.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: chaos-litmus-admin-config
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/instance: chaos
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: litmus
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/version: "3.0.0"
    helm.sh/chart: litmus-3.0.0
    litmuschaos.io/version: 3.0.0
    app.kubernetes.io/component: litmus-admin-config
data:
  INFRA_SCOPE: "cluster"
  INFRA_NAMESPACE: "observability-suite-srikanth-iyengar"
  DB_SERVER: "mongodb://chaos-mongodb-0.chaos-mongodb-headless:27017,chaos-mongodb-1.chaos-mongodb-headless:27017,chaos-mongodb-2.chaos-mongodb-headless:27017/admin"
  VERSION: "3.0.0"
  SKIP_SSL_VERIFY: "false"
---
# Source: litmus/templates/controlplane-configs.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: chaos-litmus-frontend-nginx-configuration
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/instance: chaos
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: litmus
    app.kubernetes.io/part-of: litmus
    app.kubernetes.io/version: "3.0.0"
    helm.sh/chart: litmus-3.0.0
    litmuschaos.io/version: 3.0.0
    app.kubernetes.io/component: litmus-admin-config
data:
  nginx.conf: |
    pid /tmp/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
        map $http_upgrade $connection_upgrade {
            default upgrade;
            '' close;
        }

        client_body_temp_path /tmp/client_temp;
        proxy_temp_path       /tmp/proxy_temp_path;
        fastcgi_temp_path     /tmp/fastcgi_temp;
        uwsgi_temp_path       /tmp/uwsgi_temp;
        scgi_temp_path        /tmp/scgi_temp;

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        server_tokens off;

        include /etc/nginx/mime.types;

        gzip on;
        gzip_disable "msie6";

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        server {
            listen 8185 default_server;
            root   /opt/chaos;

            location /health {
              return 200;
            }

            location / {
                proxy_http_version 1.1;
                add_header Cache-Control "no-cache";
                try_files $uri /index.html;
                autoindex on;
            }

            # redirect server error pages to the static page /50x.html
            #
            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   /usr/share/nginx/html;
            }

            location /auth/ {
                proxy_http_version 1.1;
                proxy_set_header   Host                 $host;
                proxy_set_header   X-Real-IP            $remote_addr;
                proxy_set_header   X-Forwarded-For      $proxy_add_x_forwarded_for;
                proxy_set_header   X-Forwarded-Proto    $scheme;
             proxy_pass "http://chaos-litmus-auth-server-service:9003/";
            }

            location /api/ {
                proxy_http_version 1.1;
                proxy_set_header   Host                 $host;
                proxy_set_header   X-Real-IP            $remote_addr;
                proxy_set_header   X-Forwarded-For      $proxy_add_x_forwarded_for;
                proxy_set_header   X-Forwarded-Proto    $scheme;
                proxy_pass "http://chaos-litmus-server-service:9002/";
            }

            location /ws/ {
                proxy_http_version 1.1;
                proxy_set_header   Upgrade              $http_upgrade;
                proxy_set_header   Connection           $connection_upgrade;
                proxy_set_header   Host                 $host;
                proxy_set_header   X-Real-IP            $remote_addr;
                proxy_set_header   X-Forwarded-For      $proxy_add_x_forwarded_for;
                proxy_set_header   X-Forwarded-Proto    $scheme;
                proxy_pass "http://chaos-litmus-server-service:9002/";
            }
        }
    }
