---
# Source: litmus/charts/mongodb/templates/replicaset/headless-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: chaos-mongodb-headless
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: mongodb
    helm.sh/chart: mongodb-12.1.11
    app.kubernetes.io/instance: chaos
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mongodb
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: "mongodb"
      port: 27017
      targetPort: mongodb
  selector:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: chaos
    app.kubernetes.io/component: mongodb
