version: "3"

services:
  openresty:
    image: deadcoder11u2/ntfy:latest
    volumes:
      - ./server.yml:/etc/ntfy/server.yml
      - ./supervisord.conf:/etc/supervisord.conf
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
