version: "3"

services:
  openresty:
    image: deadcoder11u2/ntfy:latest
    build:
      context: .
    volumes:
      - ./server.yml:/etc/ntfy/server.yml
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
